### ISSUE TITLE
example data meaning

### ISSUE THREAD

**Issue by williamqzc** [rafguns/linkpred#13]
I want to know what's the meaning of the third column?

**Comment by rafguns** [comment]
I assume you mean this in the README:

```
"Ikogami, K"    "Ikegami, K"    5.0
"Durand, T"     "Abd El Kader, M"       5.0
"Sharma, L"     "Kumar, S"      4.0
"Paul, A"       "Durand, T"     4.0
...
```
The number if the score for the node pair (the two names preceding it). What the score represents is dependent on the predictor. In this case (because we specified `-p CommonNeighbours`) it is the number of neighbouring nodes the two nodes have in common.

Generally speaking, the higher the score, the more related are the two nodes.
