### ISSUE TITLE
How to use linkpred for evaluation

### ISSUE THREAD

**Issue by Kiteflyingee** [rafguns/linkpred#17]
HI,I am a newcomer in the field of link prediction. I want to know how to use the tool ’linkpred‘ to evaluate related indicators. I found that there are a lot of evaluation functions built in, I call these functions but I don't get a value, but a series values,.Such as precision, will return a list of precisions. I don't know what this means? I found out in the question that you can use the sklearn package for evaluation. I don't know how to do it. Finally, is this tool related to the documentation or manual?

**Comment by rafguns** [comment]
You get a series of precision (or recall or ...) values, because link prediction yields a score for node pairs. In other words, the first value is the precision taking just the single highest ranked node pair into account, the second value is the precision taking the two highest ranked node pairs into account, etc.

If you want one value, you will have to decide on a cut-off point yourself. This is what [`PrecisionAtKListener`](https://github.com/rafguns/linkpred/blob/master/linkpred/evaluation/listeners.py#L102) does. Here, `k` is the cut-off point, i.e. the number of node pairs you want to take into account.

**Comment by rafguns** [comment]
You cannot really use sklearn at the moment; issue #3 is about enabling this and simplifying the API.

**Comment by rafguns** [comment]
Not sure if I understand your last question correctly, but [this chapter](https://repository.uantwerpen.be/docman/irua/362f55/e4f2ffec.pdf) is a basic introduction to link prediction using linkpred.
